all: p10-1 p10-2 p10-3 Ejercicio2 Ejercicio1
p10-1: p10-1.c
	gcc -O -pthread -o p10-1 p10-1.c

p10-2: p10-2.c
	gcc -O -pthread -o p10-2 p10-2.c

p10-3: p10-3.c
	gcc -O -pthread -o p10-3 p10-3.c

Ejercicio2: Ejercicio2.c
	gcc -O -pthread -o Ejercicio2 Ejercicio2.c

Ejercicio1: Ejercicio1.c
	gcc -O -pthread -o Ejercicio1 Ejercicio1.c

clean:
	rm -f p10-1 p10-2 p10-3
