all: p6-1 p6-2 p5-4 p5-5 p5-5b ejercicio2

p6-1: p6-1.c
	gcc -o p6-1 p6-1.c

p6-2: p6-2.c
	gcc -o p6-2 p6-2.c

p5-4: p5-4.c
	gcc -o p5-4 p5-4.c

p5-5: p5-5.c
	gcc -o p5-5 p5-5.c

p5-5b: p5-5b.c
	gcc -o p5-5b p5-5b.c

ejercicio2: ejercicio2.c ejercicio2b.c
	gcc -o ejercicio2 ejercicio2.c
	gcc -o ejercicio2b ejercicio2b.c

clean:
	rm -f p6-1 p6-2 p5-4 p5-5 p5-5b
