all: p7-1 p7-2 p7-3 p7-4 p5-4 p5-5 p5-5b ejercicio2

p7-1: p7-1.c
	gcc -o p7-1 p7-1.c

p7-2: p7-2.c
	gcc -o p7-2 p7-2.c

p7-3: p7-3.c
	gcc -o p7-3 p7-3.c

p7-4: p7-4.c
	gcc -o p7-4 p7-4.c

p5-4: p5-4.c
	gcc -o p5-4 p5-4.c

p5-5: p5-5.c
	gcc -o p5-5 p5-5.c

p5-5b: p5-5b.c
	gcc -o p5-5b p5-5b.c

ejercicio2: Ejercicio_2.c
	gcc -o ejercicio2 Ejercicio_2.c

clean:
	rm -f p7-1 p7-2 p7-3 p7-4 p5-4 p5-5 p5-5b
