all: p8-1 p8-2 p8-3 p8-4 ejercicio1 ejercicio2

p8-1: p8-1.c
	gcc -o p8-1 p8-1.c

p8-2: p8-2.c
	gcc -o p8-2 p8-2.c

p8-3: p8-3.c
	gcc -o p8-3 p8-3.c

p8-4: p8-4.c
	gcc -o p8-4 p8-4.c

ejercicio1: ejercicio1.c
	gcc -o ejercicio1 ejercicio1.c

ejercicio2: ejercicio2.c
	gcc -o ejercicio2 ejercicio2.c

clean:
	rm -f p8-1 p8-2 p8-3 p8-4
